### ISSUE TITLE
Selecting a node and its children to copy will copy more than expected.

### ISSUE THREAD

**Issue by izzel** [mindolph/Mindolph#4]
Selected for copy:
![mindolph 1](https://user-images.githubusercontent.com/34325651/230754218-306681fa-de27-4b92-8e01-2be6d5b3fa1b.png)

Expected:
![mindolph 3](https://user-images.githubusercontent.com/34325651/230754275-27ac8cf9-5355-4317-a5fb-958f7c57e041.png)

Actual:
![mindolph 2](https://user-images.githubusercontent.com/34325651/230754217-140f5827-d781-4c96-9b87-7a9cfad587cd.png)

**Comment by mindolph** [comment]
Will be fixed soon, for workaround, you can select just 'A' to copy&paste

**Comment by izzel** [comment]
Thank you

**Comment by mindolph** [comment]
@izzel  Please try new released version: https://github.com/mindolph/Mindolph/releases/tag/1.1.4-stable
