### ISSUE TITLE
FreeMind support (*.mm)

### ISSUE THREAD

**Issue by nigel-v-thomas** [mindolph/Mindolph#9]
I have previously used FreeMind and this project looks as though it supports FreeMind files, however on trying it I wasn't able to get it working it complains about unexpected errors when importing an existing mm file.
<img width="445" alt="Screenshot 2024-08-09 at 07 53 25" src="https://github.com/user-attachments/assets/7c7c6666-1be0-4129-9192-42588b6e3ae0">
I am using 1.0.1 version of the FreeMind files.

**Comment by mindolph** [comment]
I have reproduced the issue

**Comment by mindolph** [comment]
Please try the latest v1.7.9 stable release
